### ISSUE TITLE
Can you please provide some guidance on how to deploy an ASKCOS API server?

### ISSUE THREAD

**Issue by jackzzs** [wenhao-gao/askcos_synthesizability#2]
I've followed the official tutorial on how to deploy an ASKCOS server based on docker, but I can't access any API service but "/api/celery" according to "urls.py" in ASKCOS repo.
I wondor if you could kindly offer some guidance on how to deploy an ASKCOS API server to reproduce the results in your essay?
Thanks!

**Comment by wenhao-gao** [comment]
Sorry for the confusion. I was using an internal version of ASKCOS and just learned that the public version of ASKCOS doesn't have API access implemented a few weeks ago. As our work is sponsored by MLPDS(https://mlpds.mit.edu), we cannot release the up-to-date version to the public. We are discussing releasing a new public version with API access, and hopefully, we can do it soon.
Currently, there are several choices: 1. You can deploy the ASKCOS (easier with docker) and run it in a terminal. We can help with that, and this is sufficient for reproducing my result. 2. You can try other retrosynthetic analysis servers such as IBM_RXN or Molecule.one. I believe to measure synthesizability following my protocol, these models should be sufficient as well. Here (https://zitniklab.hms.harvard.edu/TDC/functions/oracles/#ibm-rxn-synthetic-accessibility-ibm_rxn) is an example of easy access to IBM_RXN. IBM_RXN currently has an access limit up to 5 times per minute, so this may take longer. 
Feel free to contact me through whgao@mit.edu if you need help in deploying ASKCOS. Cheers!

**Comment by jackzzs** [comment]
Thanks for your quick reply and detailed suggestions!
I will adopt the first suggestion and keep following.
